### PR TITLE
Retry diff failures (fixed by gptengineer by pasting errorrs into prompt 🔥)

### PR DESCRIPTION
**Pull request by AntonOsika**
Happy to get thorough reviewed

If you could have a look that would be awesome @similato87

### CODE REVIEW

**Comment by AntonOsika** [comment]
@similato87 do you want to merge immediately after review if it looks OK to you?

I don't want it to go stale

**Comment by similato87** [comment]
> @similato87 do you want to merge immediately after review if it looks OK to you?
> 
> I don't want it to go stale

Hi @AntonOsika, apologies for the delayed response. I was traveling throughout April until yesterday. I'll review these changes before next week, and I may need to write a few tests for this section. Increasing the self-healing steps could introduce some new scenarios.

**Review by similato87 — APPROVED** [review]
Great job on cleaning up and decoupling the functions! Your changes have really improved our codebase. I believe it's now ready for review.

**Comment by similato87** [comment]
Hi @AntonOsika . I've reviewed the changes, and everything looks good to me. Your updates effectively decouple the functions and make the refinement process more intuitive.

**Comment by viborc** [comment]
As @similato87 has reviewed this and found it to be good, I'm merging this PR.

**Pull request merged**
