### PR TITLE
Improved conversation code readability, maintainability, and robustness

### PR DESCRIPTION
**Pull request by kbshal**
**Improve readability, maintainability, and robustness of the conversation code module.**

1. Error Handling: Added error handling for file operations to make sure that specified json file exists properly

2. Input Validation: Implement input validation to check that every message dictionary has the required keys ('role', 'name', and 'content') and the 'role' key contains one of the expected values ('system', 'user', 'assistant', 'function').

3. Separation of Concerns: Refactored the code to separate the logic for loading messages from the file and formatting/printing the conversation into different functions. It improves modularity and maintainability

4. Use of List Comprehension: Utilized list comprehension to ease the creation of formatted messages, improving code readability.

5. Avoided use of formatted_messages.index(): Replaced the use of formatted_messages.index() with enumerate() to loop over the messages along with their indices,enhancing efficiency.

6. Docstrings: added descriptive docstrings on each function

### CODE REVIEW

**Review by captivus — COMMENTED** [review]
As discussed, kindly check for OpenAI API key in .env file.  Thanks!

**Comment by ATheorell** [comment]
> As discussed, kindly check for OpenAI API key in .env file. Thanks!

I think this comment was posted in the wrong PR.

**Comment by captivus** [comment]
> > As discussed, kindly check for OpenAI API key in .env file. Thanks!
> 
> 
> 
> I think this comment was posted in the wrong PR.

🤦‍♂️ clearly so.

**Comment by viborc** [comment]
> Though I like the initiative @kbshal , I'm quite puzzled by this PR:
> 
> For this (rather forgotten) script to be useful, we would first need to export AI chats in json format, somthing we currently don't do. How did you run into the usecase that this was needed in the first place?

@kbshal, can you please address @ATheorell's question (quoted above)? Otherwise, I'll be closing this issue mid-next week if I don't see any updates.

**Comment by viborc** [comment]
> Thanks for your response @kbshal ! If you are interested in contributing, the best way is to join our dev meeting 19:00 CET, which is held openly on our discord :)

Hey @kbshal - as @ATheorell said, we'd love you to join our meeting. We have them every Thursday (today, for example) at 19:00 CET. The link for our meetings is here https://discord.gg/Eq5JwSQY?event=1225505481150173335

You can join our Discord and look for me. I'll be happy to show you around, and I hope to see you join us!

**Pull request closed without merging**
